apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.global.Frontend.ServiceName }}
  namespace: {{ .Release.Namespace }}
  labels:
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app: {{ .Values.global.Frontend.ServiceName }}
spec:
  ports:
    - port: {{ .Values.global.Frontend.Port }}
      targetPort: {{ .Values.global.Frontend.Port }}
  selector:
    app: {{ .Values.global.Frontend.ServiceName }}
  type: ClusterIP
