global:
  ImageRegistry: akswsweuacr.azurecr.io
  HealthChecks:
    enabled: false
  ResourceManagement:
    enabled: false
  Frontend:
    ServiceName: frontend
    Port: 80
    BaseUrl: /
  Backend:
    ServiceName: backend
    Port: 80
    
    # Use an empty hostname to force the same host for backend and frontend
    Host: