{{- if .Values.global.ResourceManagement.enabled  }}
apiVersion: v1
kind: LimitRange
metadata:
  name: limitrange
  namespace: {{ .Release.Namespace }}
spec:
  # Prevent too big or too small containers in namespace
  # Manage values for individual containers

  limits:
  - default:
      # If not set by pod, these default limits apply
      cpu: 100m
      memory: 512Mi
    defaultRequest:
      # If not set by pod, these default requests apply
      cpu: 10m
      memory: 50Mi
    # Maximum limits that a pod can set
    max:
      cpu: 500m
      memory: 750Mi
    min:
      cpu: 10m
      memory: 50Mi
    type: Container
{{ end }}