{{- if .Values.global.ResourceManagement.enabled  }}
apiVersion: v1
kind: ResourceQuota
metadata:
  name: resourcequota
  namespace: {{ .Release.Namespace }}
spec:
  hard:
    # Applies to the whole namespace

    # Total CPU and total memory requests
    requests.cpu: "1500m"
    requests.memory: 1Gi

    # Total CPU and total memory limits
    limits.cpu: "2000m"
    limits.memory: 2Gi
{{ end }}